[build]
  publish = "dist"
  command = "npm run build"

# Handle deck subdomain - serve the React app and let React Router handle routing
[[redirects]]
  from = "https://deck.corexa.uk"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "https://deck.corexa.uk/*"
  to = "/index.html"
  status = 200
  force = true

# Serve React app for all routes (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200